### ISSUE TITLE
[SEVERE] reflectable:reflectable on lib/main.dart:

### ISSUE THREAD

**Issue by amcsoftsolutions** [merlinofcha0s/generator-jhipster-flutter#37]
Hi Cyril,

thanks for this amazing Flutter app Generator,  I have been playing around with the generator, but I get an error when I try to  to generate it, also the generated projects doesn't run.

I have attached two screens.  I have followed all the steps in your getting started post. 

building the app with this command didn't even help.
flutter pub run build_runner build
or 
 flutter pub run build_runner build --delete-conflicting-outputs

<img width="1092" alt="Screen Shot 2020-10-10 at 00 48 09" src="https://user-images.githubusercontent.com/72620213/95640286-f44ba300-0a93-11eb-857b-146083d63e52.png">
<img width="1400" alt="Screen Shot 2020-10-10 at 00 52 42" src="https://user-images.githubusercontent.com/72620213/95640288-f7df2a00-0a93-11eb-974c-080607690012.png">

**Comment by merlinofcha0s** [comment]
Hi,
Which version of flutter are you using can you do a print screen of `flutter doctor` and `flutter --version` please ?

**Comment by merlinofcha0s** [comment]
Hi,
I have found the problem, I have to upgrade dart JSON Mapper and the build runnuer
It will be available in the next version. For now, if you want to fix it on your side you can bump : 
- dart_json_mapper: 1.6.3
- build_runner: 1.10.3

I think it will work

**Comment by ahmedcatch** [comment]
Hi Cyril,
Thanks for the quick fix, I really appreciate.  I have tested and it works now, All I had to do was, to replace the new changes you have added to the  pubspec.yaml file:

and run  flutter pub run build_runner build
<img width="1440" alt="Screen Shot 2020-10-13 at 12 10 27" src="https://user-images.githubusercontent.com/64021812/95853702-be394800-0d4d-11eb-96eb-2b6339789d6e.png">

**Comment by ahmedcatch** [comment]
Hi Cyril, I have a group of 4 Juniors who are learning Flutter, and I asked them to start learning the structure of the Flutter Application your generator generates.  After that, I will ask them to learn about the generator itself  so that they can contribute the generator.  The generated mobile app, the React Web App, and the JHipster backend server project will be available on this github public repositories.  https://github.com/AMC-Software-Solution

The idea is, to developer An Online Visa Application system for Somalia which currently currently doesn't have.  We have developing and donating the system to it since we are from Somalia.   We are also making the system opensource so that anyone can use it.  The system will including and iOS and Android application developer with Flutter using your Flutter Generator.

**Comment by merlinofcha0s** [comment]
Alright, glad it worked !

That's a really nice and interesting project, thanks for choosing this generator for building this visa system app.

if you have any feedback tell me, it will be appreciate.

**Comment by ahmedcatch** [comment]
thanks we will keep you posted

**Comment by k-paxian** [comment]
@merlinofcha0s 

Hey, I've noticed you've updated `dart_json_mapper` to the latest version `1.6.3` without reading readme.
Just want to let you know there are few changes in the setup process. It would be great if you'll update them in your template.

1. Update build.yaml
```yaml
targets:
  $default:
    builders:
      dart_json_mapper:
          generate_for:
            - lib/main.dart

      # This part is needed to tell original reflectable builder to stay away
      # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - no/files
```

2. Change initialization code in `main.dart`

`import 'main.reflectable.dart';` => `import 'main.mapper.g.dart' show initializeJsonMapper;`

`initializeReflectable` => `initializeJsonMapper`

3. (Optional) In you `mapper.dart`(https://github.com/merlinofcha0s/jhipster-flutter-sample-app/blob/master/lib/mapper.dart) there is no need for your adapter anymore. Since `1.6.3` this adapter will be generated for `List<T>` and `Set<T>` on the fly as a part of 'main.mapper.g.dart' file.

4. (Optional) 
If you still need short enum converter for all enums, you could replace your custom converter with the built-in one like this:
```dart
JsonMapper().useAdapter(JsonMapperAdapter(converters: {Enum: enumConverterShort}));
```

**Comment by merlinofcha0s** [comment]
I think the changelog is not quite clear about this breaking change (https://pub.dev/packages/dart_json_mapper/changelog) and the new way of initialize the mapper in the 1.6.x.

But thanks for letting me know about this issue, for now it's okay because the [PR](https://github.com/merlinofcha0s/generator-jhipster-flutter/pull/39) for bumping all dependencies is not merged yet. So I'll make the change on this PR.

**Comment by k-paxian** [comment]
Yeah, sorry for that. Technically this is not a "breaking change" since it's not breaking anything. It's like a complementary feature accessible via those changes, otherwise it works as before.

My goal is to dissolve the need for this extra file `mapper.dart` from your side, to simplify bootstrapping and configuration process.
For now this file covers two points: 
* iterables `List<T>` `Set<T>` support [covered by builder from 1.6.3]
* enum converter for all enums having values as string [I'm thinking on making this `enumConverterShort` used by default as more intuitive] 

Thank you!

**Comment by merlinofcha0s** [comment]
I see, and I didn't notice those changes. that's very interesting I get rid of a lot of code now, especially for the entity generator. It's more elegant for the list and enum it's working out of the box !

Thanks !
